library(maptools)
library(RColorBrewer)
library(classInt)
library(OpenStreetMap)
library(sp)
library(rgeos)
library(tmap)
library(tmaptools)
library(sf)
library(rgdal)
library(geojsonio)
library(methods)

getwd()
BirminghamData<- read.csv("/Users/ziyicheng/Desktop/assignment/POP/POPdata.csv", header = TRUE, sep = ",")
class(BirminghamData)
datatypelist <- data.frame(cbind(lapply(BirminghamData,class)))
BirminghamData <- data.frame(BirminghamData)
BoroughMapSF <- read_shape("/Users/ziyicheng/Desktop/assignment/BirminghamBoundary/shapefiles/Birmingham_msoa11.shp", as.sf = TRUE)
BoroughDataMap <- append_data(BoroughMapSF,BirminghamData, key.shp = "MSOA11CD", key.data = "GEO_CODE", ignore.duplicates = TRUE)

library(ggplot2)
geom_polygon(aes(x=x, y=y), data.frame)
palette1<-scale_fill_continuous(low="white", high="orange", "Density")
labels<-labs(list(title="Birmingham Population Density",x="Longitude", y="Latitude"))

print(BoroughMapSF)
BoroughMapSF <- st_read("/Users/ziyicheng/Desktop/assignment/BirminghamBoundary/shapefiles/Birmingham_msoa11.shp") %>% st_set_crs(27700)
print(BoroughMapSF)

BoroughMapSFWGS84 <- st_transform(BoroughMapSF, 4326)
print(BoroughMapSFWGS84)
library(ggmap)
BoroughDataMap <- append_data(BoroughMapSFWGS84,BirminghamData, key.shp = "MSOA11CD", key.data = "GEO_CODE", ignore.duplicates = TRUE)
Birminghambbox1 <- c(left = -0.5103766, bottom = 51.28676, right = 0.3340146, top = 51.69187)
Birminghambbox2 <- as.vector(st_bbox(BoroughMapSFWGS84))
map <- get_stamenmap(Birminghambbox2, zoom = 10, maptype = "toner-lite")
ggmap(map) + geom_sf(mapping = aes(geometry=geometry, fill=Population..usual.residents....Density..number.of.persons.per.Hectare....Unit...Persons),data = BoroughDataMap, inherit.aes = FALSE,alpha=0.7)+theme_minimal()+palette1+labels
